# -*- coding: utf-8 -*-
"""python_programs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_sCTeC8vcqYDfHNOivpkVDD8vi12j0p
"""

print("Welcome to Siddharth sharma side/--")

a = 5
b = 6
print(a+b)
#addition

a = 9
b = 7
print(a-b)
#substraction

a = 6
b = 8
c = a*b
print(c)   # multipication

a = 88
b = 11
c = a/b
print(int(c))    #divition

# Celsius to  Fahrenheit
c = float(input())
f = (c*9/5)+32
print(f)

# Swap without third variable
a = int(input())
b = int(input())
a , b = b , a
print(a,b)

# Area of circle
r = float(input())
b = 3.14 * r * r
print(b)

# Sum of digit
a = int(input())
s = a//100 + (a//10)%10 + a%10
print("digit sum of s:",s)

# minutes & hours
m = int(input())
print(m//60,"hours",m%60,"minutes")

# simple Interest
a = int(input())
b = int(input())
c = int(input())
i = (a*b*c)/100
print(i)

# kilometers to meters
k = int(input("kilometers : "))
m = k*1000
print("meters",m)

# ASCII num
a = input()
print(ord(a))

# Number to Binary
n = input()
print(bin(int(n)))
print(oct(int(n)))

# Round float to 2 decimals
n = float(input())
print(round(n,2))

# square and cube
n = int(input())
print("square:",n*n,"cube:",n*n*n)

# Even and Odd
n = int(input())
print("EVEN"if n%2==0 else "ODD")

# Positive , Negative and Zero
n = int(input())
print("Positive" if n > 0 else "Negative" if  n < 0 else "Zero")

# Largest of Three
a,b,c = map(int,input().split())
print(max(a,b,c))

# Leap Year
y = int(input("year:"))
print("leap year" if (y%400==0 and y%100 !=0) or y%4==0 else "not leap year")

# Vowel or Consonant
ch = input().lower()
print("Vowel" if ch in "aeiou" else "consonant")

# Divisible by 3 and 5
n = int(input())
print("Yes" if n%3==0 and n%5==0 else "No")

# Grade Calculator
m = int(input())
print("A" if m>=90 else "B" if m>=75 else "C" if m>=50 else "F")

# Palindrome Number
n = input()
print("YES" if n ==n[::-1] else "NO")

# Valid Triangle
a,b,c = map(int,input().split())
print("Valid" if a+b+c==180 else "Invalid")

# Type of Triangle
a,b,c = map(int,input().split())
print("Equilateral" if a==b==c else "Isosceles" if a==b or b==c or a==c else "Scalene")

# Number of Range
n = int(input()); l,u = map(int,input().split())
print("YES" if l<=n<=u else "NO")

# Prime Number
n = int(input())
print("Prime" if n>1 and all(n%i for i in range(2,n)) else "NoT Prime")

# Voting Eligibility
age = int(input())
print("Eligibility" if age > 18 else "Not Eligible")

# Second Largest
a,b,c = map(int,input().split())
print(sorted([a,b,c])[1])

# Print 1 to 100
for i in range(101):
  print(i)

# Even numbers 1 to 50
for i in range(2,51,2):
  print(i)

# Multiplication table
n = int(input())
for i in range(1,11):
  print(n, "*", i ,"=", n*i)

# Factorial
n = int(input())
f = 1
for i in range(1,n+1):
  f = f*i
print(f)

# Count Digits
n = int(input())
count = 0
while n>0: count+=1; n//=10
print(count)

# Fibonacci
n = int(input())
a, b = 0, 1
for i in range(n+1):
  print(a); a,b=b,a+b

# Prime till 100
for n in range(2,101):
  if all(n%i for i in range(2,n)):
    print(n)

# sum of n digits
n = int(input())
print(n*(n+1)//2)

# Star pattern
n = int(input())
for i in range(1,n+1):
  print("*"*i)

# Inverted pattern
n = int(input())
for i in range(n,0,-1):
  print("*"*i)

# Armstrong Number
n=int(input()); s=0; t=n
while t>0: s+=(t%10)**3; t//=10
print("Yes" if s==n else "No")

# LCM
a,b = map(int,input().split());m = max(a,b)
while True:
  if m%a==0 and m%b==0: print(m);break
  m+=1

# GCD
a,b = map(int,input().split())
while b: a,b=b,a%b
print(a)

#sum till single digits
n = int(input())
while n>9:
  n = sum(map(int,str(n)))
print(n)

# Count Vowel
s = input();
count = 0
for i in s:
  if i.lower() in "ieaou":
    count+=1
  else:
    0
print(count)

# Reverse String
s = input()
print(s[::-1])

# Palindrome String
s = input()
print("YES" if s == s[::-1] else "NO")

# Count character Occurrences
s = input("string: "); ch = input("char: ");
c = 0
for i in s: c+=1 if i==ch else 0
print(c)

# Replace Spaces
s = input()
print(s.replace(" ","-"))

# Remove Duplicates
s = input();
res = ""
for i in s: res+=i if i not in res else ""
print(res)

# Longest WORD
s = input().split()
print(max(s,key=len))

# Anagram check
a = input();b = input()
print("YES" if sorted(a)==sorted(b) else "NO")

# Capitalize Words
s = input().split()
print(" ".join(i[0].upper()+i[1:]for i in s))

# Remove punctuation
import string
n = input();
print("".join(i for i in n if i not in string.punctuation))

# Charcter Frequency
s = input(); d ={}
for i in s : d[i]=d.get(i,0)+1
print(d)

# Substring check
s = input(); sub = input()
print("YES" if sub in s else "NO")

# Word count
s = input()
print(len(s))

# F-string Format
name = input()
age = int(input())
print(f"my name is {name}and i am {age} year old")

# Max in list
l=list(map(int,input().split()))
print(max(l))

# Second Lagest
l = list(map(int,input().split()))
print(sorted(l)[-2])

# Remove Duplicates
l = list(map(int,input().split()))
print(list(set(l)))

# Reverse list
l = list(map(int,input().split()))
print(l[::-1])

# sort without sort()
l = list(map(int,input().split()))
for i in range(len(l)):
  for j in range(i+1,len(l)):
    if l[i]>l[j]:
      l[i],l[j] = l[j],l[i]
print(l)

# Count Occurrences
l = list(map(int,input().split()));
n = int(input())
print(l.count(n))

# Common element
l1 = list(map(int,input().split()))
l2 = list(map(int,input().split()))
print(list(set(l1)&set(l2)))

# Marge list
l1 = list(map(int,input().split()))
l2 = list(map(int,input().split()))
print(l1+l2)

# Rotate list
l = list(map(int,input().split()))
k = int(input())
print(l[k:]+l[:k])

# Flatten nested list
l = eval(input())
res = []
for i in l:        # outer list ke andar ja
    for j in i:    # inner list ke elements le
        res.append(j)
print(res)

# Tuple create - change nhi hota !
t = (10,20,30)
print(t)
print(t[0])

# Tuple --> list
t = (1,2,3)
print(list(t))

# Frequency using dictionary
n = list(map(int,input().split()))
b = {}
for i in n: d[i]=d.get(i,0)+1
print(d)

# Merge Dictionaries
d1 = {1:10,2:20}
d2 = {3:30,4:40}
print({**d1, **d2})
# ** unpacking se dictionaries combine hoti hai

# Max value key
d = {'a':100,'b':200,'c':300}
print(max(d,key=d.get))  # d.get are compare value and return max.

# Remove key
d = {1:10,2:20,3:30}
d.pop(2)
print(d)

# Set union("|") & intersection("&")
a = {1,2,3}; b = {2,3,4}
print(a|b,a&b)

# Disjoint sets  ---  check karta hai ki dono me common hai ki nhi
a = {1,2}; b= {3,4}
print(a.isdisjoint(b))

# list --> Distionary
l = [10,20,30]
d = {i:l[i] for i in range(len(l))}
print(d)

# Sort dict by values
d = {1:30,2:10,3:20}
print(dict(sorted(d.items(),key=lambda x:x[0])))

# Prime Function
def isprime(n):
  return n>1 and all(n%i for i in range(2,n))
print(isprime(int(input())))

# Factorial (recursion)
def fact(n):
  return 1 if n==0 else n*fact(n-1)
print(fact(int(input())))

# Palindrome Function
def pal(n):
  return n==n[::-1]
print(pal(input()))

# Sum of list
def sumlist(n):
  return sum(n)
print(sumlist(list(map(int,input().split()))))

# Default Parameters
def greet(name="guest"):
  print("hello",name)
greet(); greet("sid")
greet("arjun")

# *args Sum
def add(*args):
  return sum(args)
print(add(1,2,3,4))

# **Kwargs
def show(**Kwargs):
  for k , v in Kwargs.items(): print(k,v)
show(a=10,b=20)
# kwargs key-value pairs leta hai aur dictionary ki tarah iterate kiya.

# Lambda Function
n = lambda x:x*2
print(n(5))

# Higher-order function
def apply(f,x):
  return f(x)
print(apply(lambda x:x+2,5))

# Fibonacci function
def fib(n):
  a,b = 0,1
  for i in range(n): print(a,end=" ");a,b=b,a+b
fib(int(input()))

# Create a class student with name and marks
class student:
  def __init__(self,name,marks):
    self.name = name
    self.marks = marks

s = student("siddharth",90)
print(s.name ,"and his marks",s.marks,"%")

# Create a class student with name and marks and grade
class student:
  def __init__(self,name,marks):
    self.name = name
    self.marks = marks
  def grade(self):
    return "A" if self.marks>=90 else "B"

s = student("siddharth",85)
print(s.name,",marks =",s.marks,",grade =",s.grade())

# Create a class Rectangle with area method
class Rectangle:
  def __init__(self,l,b):
    self.l = l
    self.b = b
  def Area(self):
    return self.l*self.b

s = Rectangle(10,20)
print(s.Area())

# Demonstrate inheritance with Animal → Dog
class animal:
  def sound(self):
    print("animal sound")

class dog(animal):
  def bark(self):
    print("dog barks")

d = dog()
d.sound()
d.bark()

# Implement encapsulation using private variable
class encap:
  def __init__(self):
    self.__x = 10

  def show(self):
    return self.__x
t = encap()
print(t.show())
# private variable (direct access nahi hota)
# Data ko hide karna = encapsulation

# Write a file
f = open("text.txt","w")
f.write("hello")
f.close()

# Read a file
f = open("text.txt","r")
print(f.read())
f.close()

# Count a line
f = open("text.txt","r")
print(len(f.readlines()))
f.close()

# TRY-EXCEPT (division)
try:
  print(10/0)
except ZeroDivisionError:
  print("error")

# Custom exception
class AgeError(Exception): pass

age = int(input())
if age<18: raise AgeError("Invalid age")

